In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])

In [3]:
print(a)

[1 2 3 4 5 6]


In [4]:
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a.ndim

1

In [6]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
b.ndim

2

In [8]:
c=np.arange(10,30)

In [9]:
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [10]:
d=np.arange(10,30)

In [12]:
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [15]:
d=np.arange(10,31,2)
print(d)

[10 12 14 16 18 20 22 24 26 28 30]


In [16]:
e=np.arange(10,29,2)

In [17]:
print(e)

[10 12 14 16 18 20 22 24 26 28]


In [18]:
e.shape=(2,5)

In [19]:
print(e)

[[10 12 14 16 18]
 [20 22 24 26 28]]


In [20]:
e.ndim

2

In [21]:
x=np.empty([3,2],dtype=int)

In [22]:
print(x)

[[-1500092448         656]
 [          0           0]
 [          1 -2147483648]]


In [23]:
x=np.zeros(10)

In [24]:
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
x=np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [26]:
y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [27]:
y[0]

array([1, 2, 3, 4])

In [28]:
y[1]

array([5, 6, 7, 8])

In [29]:
y[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
y[0:1]

array([[1, 2, 3, 4]])

In [31]:
y[2][2]

11

In [32]:
y[3][1:]

array([14, 15, 16])

In [33]:
y[:,1]

array([ 2,  6, 10, 14])

In [34]:
y[:,2]

array([ 3,  7, 11, 15])

In [35]:
y[:,0]

array([ 1,  5,  9, 13])

In [36]:
y[:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [37]:
y[1:3,0:3]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [38]:
y[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [39]:
y[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [40]:
z=y
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
